on: ["push", "pull_request"]

name: Test and report coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: npm install, npm coveralls
      continue-on-error: true
      run: |
        npm install
        npm run coverage
    - name: Coveralls
      if: always()
      uses: coverallsapp/github-action@master
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
